apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prime-test
  labels:
    group: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prime-test
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
