apiVersion: v1
kind: Service
metadata:
  name: prime-test-nodeport
  labels:
    group: api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: prime-test
