apiVersion: v1
kind: Service
metadata:
  name: prime-test-loadbalancer
  labels:
    group: api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: prime-test
