apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name.deployment }}
  labels:
    group: {{ .Values.app.group }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name.deployment }}
  minReplicas: {{ .Values.app.service.minReplicas }}
  maxReplicas: {{ .Values.app.service.maxReplicas }}
  targetCPUUtilizationPercentage: 50
