apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name.loadbalancer }}
  labels:
    group: {{ .Values.app.group }}
spec:
  type: LoadBalancer
  ports:
    - protocol: {{ .Values.app.service.protocol }}
      port: {{ .Values.app.service.externalPort }}
      targetPort: {{ .Values.app.service.internalPort }}
  selector:
    app: {{ .Values.app.name.deployment }}
