version: '3.9'

#=======================================================================================================================
#    SERVICES CONFIGURATION
#=======================================================================================================================
services:

  #-- Redis Service ----------------------------------------------------------------------------------------------------
  redis:
    container_name: 'redis'
    image: 'redis:latest'
    networks:
      default:
        aliases:
          - 'redis.prime-test.gertmuller88.dev'
          - 'cache.prime-test.gertmuller88.dev'
    expose:
      - '6379'

  #-- Primality Test Service -------------------------------------------------------------------------------------------
  prime-test:
    container_name: 'prime-test'
    image: 'gertmuller88/prime-test:latest'
    build:
      context: '..'
      dockerfile: '.docker/Dockerfile'
    environment:
      ACTIVE_PROFILE: docker-compose
    networks:
      default:
        aliases:
          - 'prime-test.gertmuller88.dev'
    expose:
      - '8080'
    ports:
      - '127.0.0.1:8080:8080/tcp'
    depends_on:
      - 'redis'

#=======================================================================================================================
#    NETWORKS CONFIGURATION
#=======================================================================================================================
networks:
  default:
    external: false
